apiVersion: v1
kind: Service
metadata:
  name: info-service
  labels:
    app.kubernetes.io/part-of: kube-itog-tsitanya
spec:
  selector:
    app: info-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
